//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialStream.ConfigTool.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SocialStream.ConfigTool.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a New Ban.
        /// </summary>
        public static string AddBanLabel {
            get {
                return ResourceManager.GetString("AddBanLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a New Query.
        /// </summary>
        public static string AddQueryLabel {
            get {
                return ResourceManager.GetString("AddQueryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The hexadecimal value of the tag that launches the in-application admin panel.
        /// </summary>
        public static string AdminByteTagGroupDescription {
            get {
                return ResourceManager.GetString("AdminByteTagGroupDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin Tag.
        /// </summary>
        public static string AdminByteTagGroupTitle {
            get {
                return ResourceManager.GetString("AdminByteTagGroupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The delay after which the in-application admin panel will disappear specified in hours, minutes and seconds. (Example format: HH:MM:SS).
        /// </summary>
        public static string AdminPanelTimeoutGroupDescription {
            get {
                return ResourceManager.GetString("AdminPanelTimeoutGroupDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin panel timeout.
        /// </summary>
        public static string AdminPanelTimeoutGroupTitle {
            get {
                return ResourceManager.GetString("AdminPanelTimeoutGroupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To change API keys, edit the configuration XML file at.
        /// </summary>
        public static string ApiKeyExplanation {
            get {
                return ResourceManager.GetString("ApiKeyExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appearance.
        /// </summary>
        public static string Appearance {
            get {
                return ResourceManager.GetString("Appearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure look-and-feel settings.
        /// </summary>
        public static string AppearanceEditorDescription {
            get {
                return ResourceManager.GetString("AppearanceEditorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The direction in which the stream animates.
        /// </summary>
        public static string AutoScrollSpeedGroupDescription {
            get {
                return ResourceManager.GetString("AutoScrollSpeedGroupDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stream direction.
        /// </summary>
        public static string AutoScrollSpeedGroupTitle {
            get {
                return ResourceManager.GetString("AutoScrollSpeedGroupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t copy background image..
        /// </summary>
        public static string BackgroundFileError {
            get {
                return ResourceManager.GetString("BackgroundFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background images must be 1920x1080 PNG files..
        /// </summary>
        public static string BackgroundFormat {
            get {
                return ResourceManager.GetString("BackgroundFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the background images for horizontal and vertical orientations of Microsoft Surface.
        /// </summary>
        public static string BackgroundImagesGroupDescription {
            get {
                return ResourceManager.GetString("BackgroundImagesGroupDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background images.
        /// </summary>
        public static string BackgroundImagesGroupTitle {
            get {
                return ResourceManager.GetString("BackgroundImagesGroupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chronological.
        /// </summary>
        public static string Chronological {
            get {
                return ResourceManager.GetString("Chronological", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\Program Files (x86)\Social Stream for Microsoft Surface\SocialStream.exe.config.
        /// </summary>
        public static string ConfigFileLocation {
            get {
                return ResourceManager.GetString("ConfigFileLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration Tool.
        /// </summary>
        public static string ConfigTool {
            get {
                return ResourceManager.GetString("ConfigTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a valid datetime in the format YYYY/MM/DD.
        /// </summary>
        public static string DateTimeError {
            get {
                return ResourceManager.GetString("DateTimeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to overwrite your changes with the default settings?.
        /// </summary>
        public static string DefaultsConfirmation {
            get {
                return ResourceManager.GetString("DefaultsConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If enabled, content will be duplicated in stream in order to maintain an even distribution of news, tweets and images..
        /// </summary>
        public static string DistributeContentGroupDescription {
            get {
                return ResourceManager.GetString("DistributeContentGroupDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distribute Content Evenly.
        /// </summary>
        public static string DistributeContentGroupTitle {
            get {
                return ResourceManager.GetString("DistributeContentGroupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string EditLabel {
            get {
                return ResourceManager.GetString("EditLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow or disallow resizing of content items. If enabled, container resizing will scale up all content within it. If disabled, content wraps instead of scaling to fit..
        /// </summary>
        public static string EnableContentResizingGroupDescription {
            get {
                return ResourceManager.GetString("EnableContentResizingGroupDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable content resizing.
        /// </summary>
        public static string EnableContentResizingGroupTitle {
            get {
                return ResourceManager.GetString("EnableContentResizingGroupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facebook.
        /// </summary>
        public static string Facebook {
            get {
                return ResourceManager.GetString("Facebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items to block from the Facebook feeds. Use &quot;@username&quot; to exclude posts from a specific user..
        /// </summary>
        public static string FacebookBansGroupDescription {
            get {
                return ResourceManager.GetString("FacebookBansGroupDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facebook bans.
        /// </summary>
        public static string FacebookBansGroupTitle {
            get {
                return ResourceManager.GetString("FacebookBansGroupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show or hide content from other users. If enabled, posts and images on the facebook page from other users are also pulled. If disabled, only content posted by the facebook page is pulled..
        /// </summary>
        public static string FacebookDisplayContentGroupDiscription {
            get {
                return ResourceManager.GetString("FacebookDisplayContentGroupDiscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display content from other users.
        /// </summary>
        public static string FacebookDisplayContentGroupTitle {
            get {
                return ResourceManager.GetString("FacebookDisplayContentGroupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure Facebook Settings.
        /// </summary>
        public static string FacebookEditorDescription {
            get {
                return ResourceManager.GetString("FacebookEditorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How often to query the Facebook for new posts specified in hours, minutes and seconds. (Example format: HH:MM:SS).
        /// </summary>
        public static string FacebookPollIntervalGroupDescription {
            get {
                return ResourceManager.GetString("FacebookPollIntervalGroupDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API polling interval.
        /// </summary>
        public static string FacebookPollIntervalGroupTitle {
            get {
                return ResourceManager.GetString("FacebookPollIntervalGroupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pages to get posts from on Facebook. Use &quot;@pagename&quot; to include posts from a specific facebook page..
        /// </summary>
        public static string FacebookQueriesGroupDescription {
            get {
                return ResourceManager.GetString("FacebookQueriesGroupDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facebook queries.
        /// </summary>
        public static string FacebookQueriesGroupTitle {
            get {
                return ResourceManager.GetString("FacebookQueriesGroupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specific words that will trigger the exclusion of a particular item from the stream.
        /// </summary>
        public static string FilteredWordsGroupDescription {
            get {
                return ResourceManager.GetString("FilteredWordsGroupDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter list.
        /// </summary>
        public static string FilteredWordsGroupTitle {
            get {
                return ResourceManager.GetString("FilteredWordsGroupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flickr.
        /// </summary>
        public static string Flickr {
            get {
                return ResourceManager.GetString("Flickr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The key for connecting to the Flickr API.
        /// </summary>
        public static string FlickrApiKeyGroupDescription {
            get {
                return ResourceManager.GetString("FlickrApiKeyGroupDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flickr API Key.
        /// </summary>
        public static string FlickrApiKeyGroupTitle {
            get {
                return ResourceManager.GetString("FlickrApiKeyGroupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items to block from the Flickr stream. Use &quot;@username&quot; to exclude images from a specific user, &quot;term&quot; to exclude a specific term, or the URL of a specific image to exclude..
        /// </summary>
        public static string FlickrBansGroupDescription {
            get {
                return ResourceManager.GetString("FlickrBansGroupDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flickr bans.
        /// </summary>
        public static string FlickrBansGroupTitle {
            get {
                return ResourceManager.GetString("FlickrBansGroupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure Flickr settings.
        /// </summary>
        public static string FlickrEditorDescription {
            get {
                return ResourceManager.GetString("FlickrEditorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How often to query the Flickr API for new images specified in hours, minutes and seconds. (Example format: HH:MM:SS).
        /// </summary>
        public static string FlickrPollIntervalGroupDescription {
            get {
                return ResourceManager.GetString("FlickrPollIntervalGroupDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API polling interval.
        /// </summary>
        public static string FlickrPollIntervalGroupTitle {
            get {
                return ResourceManager.GetString("FlickrPollIntervalGroupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms to search for on Flickr. Use &quot;@username&quot; to include images from a specific account, &quot;+groupname&quot; to include images from the pool of a specific group, or &quot;term&quot; to do a general search for that term..
        /// </summary>
        public static string FlickrQueriesGroupDescription {
            get {
                return ResourceManager.GetString("FlickrQueriesGroupDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flickr queries.
        /// </summary>
        public static string FlickrQueriesGroupTitle {
            get {
                return ResourceManager.GetString("FlickrQueriesGroupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure general application settings.
        /// </summary>
        public static string GeneralEditorDescription {
            get {
                return ResourceManager.GetString("GeneralEditorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colors must be entered in the form #AARRGGBB.
        /// </summary>
        public static string HexColorError {
            get {
                return ResourceManager.GetString("HexColorError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a valid hexadecimal number..
        /// </summary>
        public static string HexError {
            get {
                return ResourceManager.GetString("HexError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontal.
        /// </summary>
        public static string Horizontal {
            get {
                return ResourceManager.GetString("Horizontal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The minimum and maximum pixel width and height of an image. Use Load Default Settings to return to recommended values..
        /// </summary>
        public static string ImageSizeGroupDescription {
            get {
                return ResourceManager.GetString("ImageSizeGroupDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image size limits.
        /// </summary>
        public static string ImageSizeGroupTitle {
            get {
                return ResourceManager.GetString("ImageSizeGroupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whether or not the profanity filter is enabled.
        /// </summary>
        public static string IsProfanityFilterEnabledGroupDescription {
            get {
                return ResourceManager.GetString("IsProfanityFilterEnabledGroupDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable filtering.
        /// </summary>
        public static string IsProfanityFilterEnabledGroupTitle {
            get {
                return ResourceManager.GetString("IsProfanityFilterEnabledGroupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left.
        /// </summary>
        public static string Left {
            get {
                return ResourceManager.GetString("Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length.
        /// </summary>
        public static string Length {
            get {
                return ResourceManager.GetString("Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Default Settings.
        /// </summary>
        public static string LoadDefaults {
            get {
                return ResourceManager.GetString("LoadDefaults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual.
        /// </summary>
        public static string Manual {
            get {
                return ResourceManager.GetString("Manual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum.
        /// </summary>
        public static string Maximum {
            get {
                return ResourceManager.GetString("Maximum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Tag.
        /// </summary>
        public static string MicrosoftTag {
            get {
                return ResourceManager.GetString("MicrosoftTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The key for connecting to the Microsoft Tag API.
        /// </summary>
        public static string MicrosoftTagApiKeyGroupDescription {
            get {
                return ResourceManager.GetString("MicrosoftTagApiKeyGroupDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Tag API key.
        /// </summary>
        public static string MicrosoftTagApiKeyGroupTitle {
            get {
                return ResourceManager.GetString("MicrosoftTagApiKeyGroupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configures Microsoft Tag settings.
        /// </summary>
        public static string MicrosoftTagEditorDescription {
            get {
                return ResourceManager.GetString("MicrosoftTagEditorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t display any items which were posted before this date..
        /// </summary>
        public static string MinFeedItemDateGroupDescription {
            get {
                return ResourceManager.GetString("MinFeedItemDateGroupDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum Date.
        /// </summary>
        public static string MinFeedItemDateGroupTitle {
            get {
                return ResourceManager.GetString("MinFeedItemDateGroupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum.
        /// </summary>
        public static string Minimum {
            get {
                return ResourceManager.GetString("Minimum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flash the borders of items that are less than this old specified in hours, minutes and seconds. (Example format: HH:MM:SS).
        /// </summary>
        public static string NewItemAlertGroupDescription {
            get {
                return ResourceManager.GetString("NewItemAlertGroupDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New item alert.
        /// </summary>
        public static string NewItemAlertGroupTitle {
            get {
                return ResourceManager.GetString("NewItemAlertGroupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets the border color that flashes when a new item is added to the stream.
        /// </summary>
        public static string NewItemBorderColorGroupDescription {
            get {
                return ResourceManager.GetString("NewItemBorderColorGroupDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Item Alert Border Color.
        /// </summary>
        public static string NewItemBorderColorGroupTitle {
            get {
                return ResourceManager.GetString("NewItemBorderColorGroupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News.
        /// </summary>
        public static string News {
            get {
                return ResourceManager.GetString("News", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items to block from the news stream. Use &quot;@username&quot; to exclude items from a specific author, &quot;term&quot; to exclude items containing a specific term, or URLs to exclude specific news items..
        /// </summary>
        public static string NewsBansGroupDescription {
            get {
                return ResourceManager.GetString("NewsBansGroupDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News bans.
        /// </summary>
        public static string NewsBansGroupTitle {
            get {
                return ResourceManager.GetString("NewsBansGroupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure RSS feed settings.
        /// </summary>
        public static string NewsEditorDescription {
            get {
                return ResourceManager.GetString("NewsEditorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A list of URLs to RSS or ATOM feeds to poll for news items..
        /// </summary>
        public static string NewsFeedsGroupDescription {
            get {
                return ResourceManager.GetString("NewsFeedsGroupDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News feed subscriptions.
        /// </summary>
        public static string NewsFeedsGroupTitle {
            get {
                return ResourceManager.GetString("NewsFeedsGroupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets the color of the text and accents for news items.
        /// </summary>
        public static string NewsForegroundColorGroupDescription {
            get {
                return ResourceManager.GetString("NewsForegroundColorGroupDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News Foreground Color.
        /// </summary>
        public static string NewsForegroundColorGroupTitle {
            get {
                return ResourceManager.GetString("NewsForegroundColorGroupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The opacity of news items in the stream.
        /// </summary>
        public static string NewsOpacityGroupDescription {
            get {
                return ResourceManager.GetString("NewsOpacityGroupDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News item opacity.
        /// </summary>
        public static string NewsOpacityGroupTitle {
            get {
                return ResourceManager.GetString("NewsOpacityGroupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How often to check for new news items specified in hours, minutes and seconds. (Example format: HH:MM:SS).
        /// </summary>
        public static string NewsPollIntervalGroupDescription {
            get {
                return ResourceManager.GetString("NewsPollIntervalGroupDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feed polling interval.
        /// </summary>
        public static string NewsPollIntervalGroupTitle {
            get {
                return ResourceManager.GetString("NewsPollIntervalGroupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The minimum and maximum pixel width and height of news item. Use Load Default Settings to return to recommended values..
        /// </summary>
        public static string NewsSizeGroupDescription {
            get {
                return ResourceManager.GetString("NewsSizeGroupDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News item size limits.
        /// </summary>
        public static string NewsSizeGroupTitle {
            get {
                return ResourceManager.GetString("NewsSizeGroupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets the background color for news items.
        /// </summary>
        public static string NewsThemeColorGroupDescription {
            get {
                return ResourceManager.GetString("NewsThemeColorGroupDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News Background Color.
        /// </summary>
        public static string NewsThemeColorGroupTitle {
            get {
                return ResourceManager.GetString("NewsThemeColorGroupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid number..
        /// </summary>
        public static string NumberError {
            get {
                return ResourceManager.GetString("NumberError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social Stream for Microsoft® Surface®.
        /// </summary>
        public static string ProductName {
            get {
                return ResourceManager.GetString("ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profanity Filter.
        /// </summary>
        public static string ProfanityFilter {
            get {
                return ResourceManager.GetString("ProfanityFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure words and phrases to filter out.
        /// </summary>
        public static string ProfanityFilterDescription {
            get {
                return ResourceManager.GetString("ProfanityFilterDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queries may not include the &quot;|&quot; character..
        /// </summary>
        public static string QueryStringComma {
            get {
                return ResourceManager.GetString("QueryStringComma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queries may not be empty..
        /// </summary>
        public static string QueryStringEmpty {
            get {
                return ResourceManager.GetString("QueryStringEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random.
        /// </summary>
        public static string Random {
            get {
                return ResourceManager.GetString("Random", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset to default categories.
        /// </summary>
        public static string ResetCategoriesLabel {
            get {
                return ResourceManager.GetString("ResetCategoriesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defines the order in which items are displayed.
        /// </summary>
        public static string RetrievalOrderGroupDescription {
            get {
                return ResourceManager.GetString("RetrievalOrderGroupDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content display order.
        /// </summary>
        public static string RetrievalOrderGroupTitle {
            get {
                return ResourceManager.GetString("RetrievalOrderGroupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right.
        /// </summary>
        public static string Right {
            get {
                return ResourceManager.GetString("Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please correct the errors highlighted in red before saving..
        /// </summary>
        public static string SaveError {
            get {
                return ResourceManager.GetString("SaveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a size in the format: width,length.
        /// </summary>
        public static string SizeError {
            get {
                return ResourceManager.GetString("SizeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets the color of the text and accents for content from social networks.
        /// </summary>
        public static string SocialForegroundColorGroupDescription {
            get {
                return ResourceManager.GetString("SocialForegroundColorGroupDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social Foreground Color.
        /// </summary>
        public static string SocialForegroundColorGroupTitle {
            get {
                return ResourceManager.GetString("SocialForegroundColorGroupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets the background color for content from social networks.
        /// </summary>
        public static string SocialThemeColorGroupDescription {
            get {
                return ResourceManager.GetString("SocialThemeColorGroupDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social Background Color.
        /// </summary>
        public static string SocialThemeColorGroupTitle {
            get {
                return ResourceManager.GetString("SocialThemeColorGroupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The minimum and maximum pixel width and height of a Tweet. Use Load Default Settings to return to recommended values..
        /// </summary>
        public static string StatusSizeGroupDescription {
            get {
                return ResourceManager.GetString("StatusSizeGroupDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tweet size limits.
        /// </summary>
        public static string StatusSizeGroupTitle {
            get {
                return ResourceManager.GetString("StatusSizeGroupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag series.
        /// </summary>
        public static string TagSeriesHeader {
            get {
                return ResourceManager.GetString("TagSeriesHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag value.
        /// </summary>
        public static string TagValueHeader {
            get {
                return ResourceManager.GetString("TagValueHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a valid time in the format HH:MM:SS.
        /// </summary>
        public static string TimeSpanError {
            get {
                return ResourceManager.GetString("TimeSpanError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The opacity of tweets in the stream.
        /// </summary>
        public static string TweetOpacityGroupDescription {
            get {
                return ResourceManager.GetString("TweetOpacityGroupDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tweet opacity.
        /// </summary>
        public static string TweetOpacityGroupTitle {
            get {
                return ResourceManager.GetString("TweetOpacityGroupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twitter.
        /// </summary>
        public static string Twitter {
            get {
                return ResourceManager.GetString("Twitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items to block from the Twitter stream. Use &quot;@username&quot; to exclude tweets from a specific user, &quot;term&quot; to exclude a specific term, or the URL of a specific tweet to exclude..
        /// </summary>
        public static string TwitterBansGroupDescription {
            get {
                return ResourceManager.GetString("TwitterBansGroupDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twitter bans.
        /// </summary>
        public static string TwitterBansGroupTitle {
            get {
                return ResourceManager.GetString("TwitterBansGroupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure Twitter settings.
        /// </summary>
        public static string TwitterEditorDescription {
            get {
                return ResourceManager.GetString("TwitterEditorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How often to query the Twitter API for new tweets specified in hours, minutes and seconds. (Example format: HH:MM:SS).
        /// </summary>
        public static string TwitterPollIntervalGroupDescription {
            get {
                return ResourceManager.GetString("TwitterPollIntervalGroupDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API polling interval.
        /// </summary>
        public static string TwitterPollIntervalGroupTitle {
            get {
                return ResourceManager.GetString("TwitterPollIntervalGroupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms to search for on Twitter. Use &quot;@username&quot; to include tweets from a specific account, &quot;to:username&quot; to include tweets to a specific account, &quot;#term&quot; to include a hashtag, and &quot;term&quot; to do a general search for that term..
        /// </summary>
        public static string TwitterQueriesGroupDescription {
            get {
                return ResourceManager.GetString("TwitterQueriesGroupDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twitter queries.
        /// </summary>
        public static string TwitterQueriesGroupTitle {
            get {
                return ResourceManager.GetString("TwitterQueriesGroupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid URL..
        /// </summary>
        public static string UriError {
            get {
                return ResourceManager.GetString("UriError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical.
        /// </summary>
        public static string Vertical {
            get {
                return ResourceManager.GetString("Vertical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets the color of the contact visualization when the display is touched.
        /// </summary>
        public static string VisualizationColorGroupDescription {
            get {
                return ResourceManager.GetString("VisualizationColorGroupDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visualization Color.
        /// </summary>
        public static string VisualizationColorGroupTitle {
            get {
                return ResourceManager.GetString("VisualizationColorGroupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width.
        /// </summary>
        public static string Width {
            get {
                return ResourceManager.GetString("Width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
